name: Sync all branches
on:
  workflow_dispatch:

jobs:

  generate-matrix:
    name: Generate matrix of branches
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix of branches
        id: set-matrix
        run: |
          upstream_repo="https://github.com/${INPUT_UPSTREAM_REPOSITORY}.git"

          # these jq scripts will produce the same matrix jobs by default
          # choose the one that works for any additional values that you may need to build your matrix with
          jq_script='{ "branch": [inputs | split("\n") | .[] | gsub(".*refs/heads/"; "")] }'   # {"branch":["$branch_name_1","$branch_name_2"]}
          # jq_script='[inputs | split("\n") | .[] | gsub(".*refs/heads/"; "") | { "branch": . }]' # [{"branch":"$branch_name_1"},{"branch":"$branch_name_2"}]

          JSON="$(git ls-remote --heads "$upstream_repo" | jq -McnR "$jq_script")"

          # debug matrix pretty json formatted output
          jq --monochrome-output . -- <<< "$JSON"

          # set output variable named 'matrix' for use in subsequent jobs that 'needs' this job.
          # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
          echo "::set-output name=matrix::$JSON"

        env:
          INPUT_UPSTREAM_REPOSITORY: balena-labs-projects/balena-sound

  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
      fail-fast: false
    name: Sync latest commits from upstream repo

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          lfs: true
          token: ${{ secrets.SEC_TOKEN }}

      - name: Set git identity
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Load upstream commits
        env:
          UPSTREAM_BRANCH: ${{ matrix.branch }}
          UPSTREAM_REPO: balena-labs-projects/balena-sound
        run: |
          git remote add upstream https://github.com/$UPSTREAM_REPO
          git fetch upstream
          git rebase upstream/$UPSTREAM_BRANCH

      - name: Push Commits
        env:
          DOWNSTREAM_BRANCH: ${{ matrix.branch }}
        run: git push --force-with-lease --follow-tags --tags origin $DOWNSTREAM_BRANCH
